### ISSUE TITLE
Make `poll` optional in upload

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/LokaliseGradlePlugin#61]
Currently we are waiting for the upload to be completed to finish the Gradle task.
See https://github.com/ioki-mobility/LokaliseGradlePlugin/blob/c08ce4b0cd3806cee36fbafaa4ef16908840c74b/src/main/kotlin/com/ioki/lokalise/gradle/plugin/tasks/UploadTranslationsTask.kt#L75

Me might want to introduce this as an optional property.
Meaning we will just push each and every file to Lokalise and finish the task without checking the results of each upload...

**Comment by juschmitt** [comment]
I will try to tackle this. If you have more info about this or what I need to look out for please let me know.

**Comment by StefMa** [comment]
Nice to hear! Thank you.

The todos here are mainly:
* Add a new "poll" option to the Extension
* Put the option to the task
* Depending on if the option is set, call `LokaliseApi.checkProcess` or not

Up to date check:
The property should be declared as an input of the task. As if it changes, the task should not be up-to-date anymore.

I guess that's it 🤔 🙃
