### ISSUE TITLE
Add downloadFiles functionality to `LokaliseApi`

### ISSUE THREAD

**Issue by juschmitt** [ioki-mobility/LokaliseGradlePlugin#69]
>  💭 Since the `LokaliseApi` is a wrapper around the `Lokalise` object from our dependency, we might want to add `downloadFiles` to this too..
> Then we can also use this class in the `DownloadTask` then..

_Originally posted by @StefMa in https://github.com/ioki-mobility/LokaliseGradlePlugin/pull/67#discussion_r1518657930_

**Comment by juschmitt** [comment]
@StefMa I was thinking if it would make sense to have a second interface for `downloadFiles`. Something like `LokaliseDownloadApi` (and renaming the existing one to `LokaliseUploadApi`).

That way we would have some separation of concerns for the Api calls. 
DownloadTask having access only to the download api, while the UploadTask has access to the upload api only...

What do you think?

**Comment by StefMa** [comment]
Sure thing, give it a try 👍 
Lets see how it will look like.
